name = "wazweather"
main = "worker.js"
compatibility_date = "2024-05-26"

[build]
command = "bash build.sh"

[assets]
directory = "output/wwwroot"
not_found_handling = "single-page-application"
include = ["**/*"]

[[kv_namespaces]]
binding = "CRON_STATE"
id = "mock-id-for-local-dev" # You should update this with real KV id
